#!/bin/bash

export OPENEXR_VER=1.2.2

# needs work to support newer arches
export A2PS_VER=4.13b

export A52DEC_VER=0.7.4
export AALIB_VER=1.4rc4
export ALSA_LIB_VER=1.0.8
export ALSA_TOOLS_VER=1.0.8
export ALSA_UTILS_VER=1.0.8

# see notes concerning issues
export ASPELL_VER=0.60.2		# needs wrapper

export CDPARANOIA_VER=alpha9.8 
export CDK_VER=5.0-20050424
export CUPS_VER=1.1.23			# needs wrapper

export DBUS_VER=0.33
export DT_FILE_UTILS_VER=0.10
export DBK_DSSSL_VER=1.79
#export DBK_SGML_VER=4.4
export DBK_SGML_VER=3.1
export DBK_UTILS_VER=0.6.14

# check script can handle version, see notes
export DBK_XML_DTD_VER=4.4
# check script can handle version, see notes
export DBK_XSL_VER=1.67.2
export DBUS_VER=0.35.2

export DIRECTFB_VER=0.9.22

export DOXYGEN_VER=1.4.2
export ED_VER=0.2
export EXIF_VER=0.6.9
export ENSCRIPT_VER=1.6.4

export ESPGS_VER=7.07.1
export GS_FONTS_STD_VER=8.11
export GS_FONTS_OTHER_VER=6.0

export FAM_VER=

export FAAC_VER=1.24
export FAAD2_VER=2.0
export FLAC_VER=1.1.2
export FFMPEG_VER=20050806
export FFTW_VER=2.1.5
export FFTW3_VER=3.0.1
export FLTK_VER=1.1.6			# needs wrapper

# Foomatic filter setup for cups is gonna need work... 
# check if CC/CFLAGS need to be defined
export FOOMATIC_DB_VER=20050514
export FOOMATIC_DB_HPIJS_VER=1.5
export FOOMATIC_FILTERS_VER=3.0.2
export FOOMATIC_DB_ENG_VER=3.0.2

export FREEGLUT_VER=2.2.0

export GAMIN_VER=0.1.1

export GD_VER=2.0.33			# needs wrapper
export GDBM_VER=1.8.3
export GEXIF_VER=0.5
export GIFLIB_VER=4.1.3
export GIMP_PRINT_VER=4.2.7		# needs wrapper
export GLIB12_VER=1.2.10		# needs wrapper
export GPHOTO2_VER=2.1.6

# check LIBPOSTFIX in configure for mips
export GRAPHVIS_VER=2.2.1		# needs wrapper 

export GSM_VER=1.0.10

export GTK12_VER=1.2.10			# needs wrapper
export HAL_VER=0.5.3
export HC_ICON_THEME_VER=0.8
export HOWL_VER=1.0.0
export ID3LIB_VER=3.8.3
export IJS_VER=0.35			# needs wrapper
export IMLIB2_VER=1.2.1
export JADETEX_VER=3.13
export JASPER_VER=1.701.0

# lcms has issues... see notes
export LCMS_VER=1.14

export LAME_VER=3.96.1

# check notes on need to edit mxmkmf
export LESSTIF_VER=0.94.4		# needs wrapper 

export LIBAO_VER=0.8.6
export LIBCACA_VER=0.9
export LIBDVDCSS_VER=1.2.9

export LIBEXIF_VER=0.6.12
export LIBEXIFGTK_VER=0.3.5
export LIBFAME_VER=0.9.1
export LIBGPHOTO2_VER=2.1.6
export LIBIDN_VER=0.5.16

export LIBIEEE1284_VER=0.2.10
# libjpeg is a GODDAMNED FIGHT building on x86_64, needs fixing
export LIBJPEG_VER=v6b

export LIBMAD_VER=0.15.1b
#export LIBMIKMOD_VER=3.2.0-beta2
export LIBMIKMOD_VER=3.1.11
export LIBMODPLUG_VER=0.7

# Check setting of PREFIX for header fixups, check setting of MACHINE
export LIBMPEG3_VER=1.5.4

export LIBMNG_VER=1.0.9
export LIBNTLM_VER=0.3.7

export LIBOGG_VER=1.1.2
export LIBPAPER_VER=1.1.14

# requires a device node created... revisit for udev
export LIBRAW1394_VER=1.2.0
export LIBSNDFILE_VER=1.0.12oggflac
export LIBSAMPLERATE_VER=0.1.2

export LIBTHEORA_VER=1.0alpha4
export LIBUSB_VER=0.1.10a
export LIBVORBIS_VER=1.1.0
export LIBXVMCW_VER=0.9.3

# Additional requirements, see script
export LM_SENSORS_VER=2.9.1

export LYNX_VER=2.8.5

# Check patch requirements for amd64 etc... check script for other needed fixes
export MAS_VER=0.6.3			# Needs wrapper

export MDNS_VER=107.1
export MTOOLS_VER=3.9.10
export MYSQL_VER=4.1.11			# needs wrapper and header mods
export NAS_VER=1.7

# double check this script... only builds 32
export NASM_VER=0.98.38

export NCOMPRESS_VER=4.2.4

# libtool barfage, may be fixed now...
export OPENJADE_VER=1.3.2  
export OPENSP_VER=1.5.1			# needs header fixes
export PCRE_VER=5.0			# needs wrapper
export PGSQL_VER=8.0.3
export PKGCONFIG_VER=0.17.2
export POPT_VER=1.7
export POLYPAUDIO_VER=0.7

# check setting CC is correct...
export PSUTILS_VER=p17

# will probably need edits for lib32
export PYTHON_VER=2.4.1
export PYREX_VER=0.9.3

# Much more needs to be done for mips etc
# needs wrapper and header mods
# Also note the QT_INSTALL_SELF_CVONTAINED env var for putting it in /opt
export QT_VER=3.3.4

#revisit this script re --with-libdir= vs --libdir=
export SAMBA_VER=3.0.14a
export SANE_BACKENDS_VER=1.0.15
export SDL_VER=1.2.8
export SGML_COMMON_VER=0.6.3
export SGMLSPM_VER=1.03ii
export SHARUTILS_VER=4.3.80
export SHD_MIME_INFO_VER=0.16
export SLANG_VER=1.4.9
export SPEEX_VER=1.1.10

# TODO: Look into swig builds when multilib... read script for details
#       Work will need to be done, script hasn't been touched
export SWIG_VER=1.3.24
export SYSFSUTILS_VER=1.3.0

export T1LIB_VER=5.1.0
export TETEX_VER=3.0
export TIFF_VER=3.7.2
export TK_VER=8.4.9
export TK_PM_VER=804.027
export UNIXODBC_VER=2.2.11
# Check unzip to see how to apply target specific cflags, default env etc
export UNZIP_VER=552

export WINE_VER=20050628
export WHICH_VER=2.16
export X264_VER=svn-20050731
export XINE_LIB_VER=1.1.0
export XINE_UI_VER=0.99.4
export XMLTO_VER=0.0.18
export XMMS_VER=1.2.10			# needs wrapper
export XPDF_VER=3.00

# need to make sure perl uses a wrapper
export XML_PARSER_PM_VER=2.34
export XVID_VER=1.1.0-beta2

export YASM_VER=0.4.0

export ZIP_VER=231
