#!/bin/sh
########################################################################
# Begin $rc_base/init.d/network
#
# Description : Network Control Script
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
#		Nathan Coulson - nathan@linuxfromscratch.org
#		Kevin P. Fleming - kpfleming@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}
. /etc/sysconfig/network

case "${1}" in
	stop)
		# Stop all network interfaces
		IFACE="`ls /sys/class/net`"
		for interface in $IFACE
		do
			if [ "$interface" != "lo" ]; then
				IN_BOOT=1 ${network_devices}/ifdown ${interface}
			fi
		done
		;;

	*)
		echo "Usage: ${0} {stop}"
		exit 1
		;;
esac

# End /etc/rc.d/init.d/network
