#!/bin/bash

export OPENEXR_VER=1.2.1

# needs work to support newer arches
export A2PS_VER=4.13b

export A52DEC_VER=0.7.4
export ALSA_LIB_VER=1.0.8
export ALSA_TOOLS_VER=1.0.8
export ALSA_UTILS_VER=1.0.8

# see notes concerning issues
export ASPELL_VER=0.60			# needs wrapper

export CDPARANOIA_VER=alpha9.8 
export CUPS_VER=1.1.23			# needs wrapper
export DBUS_VER=
export DT_FILE_UTILS=0.10
export DBK_DSSL_VER=1.79
export DBK_SGML_VER=3.1

# check script can handle version, see notes
export DBK_XML_DTD_VER=4.4
# check script can handle version, see notes
export DBK_XSL_VER=1.67.2

export DOXYGEN_VER=1.4.1
export ED_VER=0.2
export ENSCRIPT_VER=1.6.4
export ESPGS=7.07.1
export FAM_VER=

# TODO: single, double options not being set
export FFTW_VER=2.1.5

export FFTW3_VER=3.0.1
export FLTK_VER=1.1.6			# needs wrapper

# Foomatic filter setup for cups is gonna need work... 
# check if CC/CFLAGS need to be defined
export FOOMATIC_DB_VER=
export FOOMATIC_DB_HPIJS_VER=1.5
export FOOMATIC_FILTERS_VER=3.0.2
export FOOMATIC_DB_ENG_VER=3.0.2

export FREEGLUT=2.2.0

# TODO: re-enable inotify support
export GAMIN_VER=0.0.22

export GD_VER=2.0.33			# needs wrapper
export GDBM_VER=1.8.3
export GIMP_PRINT_VER=4.2.7		# needs wrapper
export GLIB12=1.2.10				# needs wrapper

# check LIBPOSTFIX in configure for mips
export GRAPHVIS_VER=2.2			# needs wrapper 

export GTK12_VER=1.2.10			# needs wrapper
export HC_ICON_THEME_VER=0.5
export IJS_VER=0.35			# needs wrapper
export JADETEX_VER=3.13
export JASPER=1.701.0

# lcms has issues... see notes
export LCMS_VER=1.14

# check notes on need to edit mxmkmf
export LESSTIF=0.94.0			# needs wrapper 

# hmmm isn't this part of glibc nowadays
export LIBIDN_VER=0.5.9

# libjpeg is a GODDAMNED FIGHT building on x86_64, needs fixing
export LIBJPEG_VER=v6b

export LIBMAD_VER=0.15.1b
export LIBMIKMOD_VER=3.1.11		# needs wrapper

# Check setting of PREFIX for header fixups, check setting of MACHINE
export LIBMPEG3_VER=1.5.4

export LIBOGG_VER=1.1.2

# requires a device node created... revisit for udev
export LIBRAW1394_VER=1.1.0

export LIBVORBIS_VER=1.1.0

# Additional requirements, see script
export LM_SENSORS_VER=2.9.0

# Check patch requirements for amd64 etc... check script for other needed fixes
export MAS_VER=0.6.3			# Needs wrapper

export MTOOLS_VER=3.9.9
export MYSQL_VER=4.1.9			# needs wrapper and header mods
export NAS_VER=1.7

# double check this script... only builds 32
export NASM_VER=0.98.38

# libtool barfage, may be fixed now...
export OPENJADE_VER=1.3.2  
export OPENSP_VER=1.5.1			# needs header fixes
export PCRE_VER=5.0			# needs wrapper
export PKGCONFIG_VER=
export POPT_VER=1.7

# check setting CC is correct...
export PSUTILS_VER=p17

# needs wrapper and also header mods (wrapper may not cut it)
# Also will probably need edits for lib32
export PYTHON_VER=2.4

# Much more needs to be done for mips etc
# needs wrapper and header mods
# Also note the QT_INSTALL_SELF_CVONTAINED env var for putting it in /opt
export QT_VER=3.3.4

#revisit this script re --with-libdir= vs --libdir=
export SAMBA_VER=3.0.11
export SGML_COMMON_VER=0.6.3
export SGMLSPM_VER=1.03ii
export SHD_MIME_INFO_VER=0.15

# TODO: Look into swig builds when multilib... read script for details
#       Work will need to be done, script hasn't been touched
export SWIG_VER=

export TETEX_VER=2.0.2
export TIFF_VER=3.7.1
export TK_VER=8.4.9

# Check unzip to see how to apply target specific cflags, default env etc
export UNZIP_VER=551

export WHICH_VER=2.16
export XMMS_VER=1.2.10			# needs wrapper

# need to make sure perl uses a wrapper
export XML_PARSER_VER=   
