#!/bin/bash

export OPENEXR_VER=

# needs work to support newer arches
export A2PS_VER=

export A52DEC_VER=
export ALSA_LIB_VER=
export ALSA_TOOLS_VER=
export ALSA_UTILS_VER=

# see notes concerning issues
export ASPELL_VER=			# needs wrapper

export CDPARANOIA_VER= 
export CUPS_VER=			# needs wrapper
export DBUS_VER=
export DT_FILE_UTILS=
export DBK_DSSL_VER=
export DBK_SGML_VER=

# check script can handle version, see notes
export DBK_XML_DTD_VER=   
# check script can handle version, see notes
export DBK_XSL_VER=

export DOXYGEN_VER=   
export ED_VER=
export ENSCRIPT_VER=
export ESPGS=
export FAM_VER=

# TODO: single, double options not being set
export FFTW_VER=

export FFTW3_VER=
export FLTK_VER=			# needs wrapper

# Foomatic filter setup for cups is gonna need work... 
# check if CC/CFLAGS need to be defined
export FOOMATIC_DB_VER=
export FOOMATIC_DB_HPIJS_VER=
export FOOMATIC_FILTERS_VER=
export FOOMATIC_DB_ENG_VER=

export FREEGLUT=

# TODO: re-enable inotify support
export GAMIN_VER=

export GD_VER=				# needs wrapper
export GDBM_VER=
export GIMP_PRINT_VER=			# needs wrapper
export GLIB12=				# needs wrapper

# check LIBPOSTFIX in configure for mips
export GRAPHVIS_VER=			# needs wrapper 

export GTK12_VER=			# needs wrapper
export HC_ICON_THEME_VER=
export IJS_VER=				# needs wrapper
export JADETEX_VER=
export JASPER=

# lcms has issues... see notes
export LCMS_VER=   

# check notes on need to edit mxmkmf
export LESSTIF=				# needs wrapper 

# hmmm isn't this part of glibc nowadays
export LIBIDN_VER=   

# libjpeg is a GODDAMNED FIGHT building on x86_64, needs fixing
export LIBJPEG_VER=

export LIBMAD_VER=
export LIBMIKMOD_VER=			# needs wrapper

# Check setting of PREFIX for header fixups, check setting of MACHINE
export LIBMPEG3_VER=

export LIBOGG_VER=

# requires a device node created... revisit for udev
export LIBRAW1394_VER=

export LIBVORBIS_VER=

# Additional requirements, see script
export LM_SENSORS_VER=

# Check patch requirements for amd64 etc... check script for other needed fixes
export MAS_VER=				# Needs wrapper

export MTOOLS_VER=
export MYSQL_VER=			# needs wrapper and header mods
export NAS_VER=

# double check this script... only builds 32
export NASM_VER=

# libtool barfage, may be fixed now...
export OPENJADE_VER=  
export OPENSP_VER=			# needs header fixes
export PCRE_VER=			# needs wrapper
export PKGCONFIG_VER=
export POPT_VER=

# check setting CC is correct...
export PSUTILS_VER=

# needs wrapper and also header mods (wrapper may not cut it)
# Also will probably need edits for lib32
export PYTHON_VER=

# Much more needs to be done for mips etc
# needs wrapper and header mods
# Also note the QT_INSTALL_SELF_CVONTAINED env var for putting it in /opt
export QT_VER=

#revisit this script re --with-libdir= vs --libdir=
export SAMBA_VER=
export SGML_COMMON_VER=
export SGMLSPM_VER=
export SHD_MIME_INFO_VER=

# TODO: Look into swig builds when multilib... read script for details
#       Work will need to be done, script hasn't been touched
export SWIG_VER=

export TETEX_VER=
export TIFF_VER=
export TK_VER=

# Check unzip to see how to apply target specific cflags, default env etc
export UNZIP_VER=

export WHICH_VER=
export XMMS_VER=			# needs wrapper

# need to make sure perl uses a wrapper
export XML_PARSER_VER=   
